UPFleet/Controllers/MaintenanceController.cs
using Microsoft.AspNetCore.Http;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using UPFleet.Models;
using UPFleet.Repositories;
using UPFleet.ViewModels;

namespace UPFleet.Controllers
{
    public class MaintenanceController : Controller
    {
        private readonly IRepository _repository;
        public MaintenanceController()
        {
            _repository = new Repository();
        }

        public ActionResult OwnerUpdate(int Id)
        {
            List<Owner> ownerList = _repository.GetOwnerList().ToList();

            int currentIndex = ownerList.FindIndex(m => m.ID == Id);

            if (currentIndex >= 0)
            {
                Owner obj = ownerList[currentIndex];
                int totalRecords = ownerList.Count;

                TempData["data"] = totalRecords;

                // Create an anonymous object that includes the currentIndex
                obj.CurrentIndex = currentIndex;

                return View(obj);
            }
            else
            {
                return RedirectToAction("OwnerUpdate", new { Id = Id + 1 });
            }
        }



        [HttpPost]
        public ActionResult OwnerUpdate(Owner model)
        {
            if (ModelState.IsValid)
            {
                if (_repository.GetOwnerList().Any(m => m.ID == model.ID && m.OwnerName == model.OwnerName))
                {
                    var result = _repository.UpdateOwner(model);
                    if (!result)
                    {
                        throw new Exception("Internal Issue Found. Try Again after some time.");
                    }
                    return RedirectToAction("OwnerUpdate", new { Id = model.ID });
                }
                else
                {
                    Owner obj = new Owner()
                    {
                        OwnerName = model.OwnerName,
                        Company = model.Company,
                        Account = model.Account
                    };
                    var result = _repository.AddOwner(obj);
                    if (!result)
                    {
                        throw new Exception("Internal Issue Found. Try Again after some time.");
                    }
                    int maxid = _repository.GetOwnerList().Max(m => m.ID);
                    return RedirectToAction("OwnerUpdate", new { Id = maxid });
                }
            }
            return RedirectToAction("OwnerUpdate", new { Id = model.ID });
        }

        public ActionResult AutocompleteBarge(string term)
        {
            List<string> suggestions = new List<string>();
            suggestions = _repository.GetBargeNameList(term);

            return Json(suggestions, JsonRequestBehavior.AllowGet);

        }
        public ActionResult AutocompleteOwner(string term)
        {
            List<string> suggestions = new List<string>();
            suggestions = _repository.GetOwnerList().Where(b => b.OwnerName.ToLower().Contains(term.ToLower())).Select(b => b?.OwnerName).ToList();

            return Json(suggestions, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CreateBarge()
        {
            var Ownerslist = _repository.GetOwnerList().OrderBy(m => m?.OwnerName).ToList();
            ViewBag.message = Ownerslist;
            return View();
        }
        [HttpPost]
        public ActionResult CreateBarge(Barge model)
        {
            if (model != null)
            {
                if (ModelState.IsValid)
                {
                    Barge obj = new Barge()
                    {
                        Barge_Name = model.Barge_Name,
                        Size = model.Size,
                        Description = model.Description,
                        Rate = model.Rate,
                        Owner = model.Owner
                    };
                    var result = _repository.AddBarge(obj);
                    if (!result)
                    {
                        throw new Exception("Internal Issue Found. Try Again after some time.");
                    }
                    return RedirectToAction("IndexPage", "Home", new { BargeName = model.Barge_Name });
                }
            }
            return View();
        }

        public ActionResult ExportBargesToExcel()
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            // Retrieve all Barge data from your data source (e.g., database)
            var barges = _repository.GetBargeList().OrderBy(m => m.Barge_Name).ToList();

            // Create an Excel package using EPPlus
            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("Barges");

                var headers = typeof(Barge).GetProperties();
                for (int col = 1; col <= headers.Length - 2; col++)
                {
                    worksheet.Cells[1, col].Value = headers[col].Name;
                }

                // Add data
                for (int row = 2; row <= barges.Count() + 1; row++)
                {
                    for (int col = 1; col <= headers.Length - 2; col++)
                    {
                        worksheet.Cells[row, col].Value = headers[col].GetValue(barges[row - 2]);
                    }
                }
                // Save the Excel package to a stream
                using (var memoryStream = new MemoryStream())
                {
                    package.SaveAs(memoryStream);
                    var excelBytes = memoryStream.ToArray();

                    // Set response headers
                    var contentDisposition = new ContentDisposition
                    {
                        FileName = "Barges.xlsx",
                        Inline = false
                    };

                    Response.Headers.Add("Content-Disposition", contentDisposition.ToString());
                    Response.Headers.Add("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");

                    // Return the Excel bytes as a FileContentResult
                    return new FileContentResult(excelBytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                    {
                        FileDownloadName = "Barges.xlsx"
                    };
                }
            }
        }
        [HttpPost]
        public ActionResult CheckDuplicateBarge(HttpPostedFileBase excelFile)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            if (excelFile != null && excelFile.ContentLength > 0)
            {
                try
                {
                    // Use a library like EPPlus or ClosedXML to read the Excel file
                    using (var package = new ExcelPackage(excelFile.InputStream))
                    {
                        var worksheet = package.Workbook.Worksheets[0];
                        var bargeNames = worksheet.Cells[2, 1, worksheet.Dimension.Rows, 1]
                                             .Select(cell => cell.Value?.ToString())
                                             .Where(name => !string.IsNullOrEmpty(name))
                                             .ToList();

                        var existingBargeNames = new HashSet<string>(_repository.GetBargeList().Select(b => b.Barge_Name));
                        var duplicates = bargeNames.Where(name => existingBargeNames.Contains(name)).ToList();

                        var totalnewbargescount = bargeNames.Count() - duplicates.Count();
                        if (duplicates.Count > 0)
                        {
                            return Json(new { isDuplicate = true, message = "Duplicate barge names found: " + string.Join(", ", duplicates), totalduplicatebarge = duplicates.Count(), totalnewbarges = totalnewbargescount }, JsonRequestBehavior.AllowGet);
                        }
                        else
                        {
                            return Json(new { isDuplicate = false }, JsonRequestBehavior.AllowGet);
                        }
                    }
                }
                catch (Exception)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "An error occurred during duplicate check.");
                }
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "An error occurred importing. Please try again later.");
            }
        }



        [HttpPost]
        public ActionResult ImportBargesFromExcel(IFormFile excelFile)
        {
            // Validate the uploaded file
            if (excelFile == null || excelFile.Length <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "No file uploaded.");
            }
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            try
            {
                using (var stream = excelFile.OpenReadStream())
                {
                    // Use a library like EPPlus or ClosedXML to read the Excel file
                    using (var package = new ExcelPackage(stream))
                    {
                        var worksheet = package.Workbook.Worksheets[0];

                        // Assuming the data starts from row 2 (header in row 1)
                        for (int row = 2; row <= worksheet.Dimension.Rows; row++)
                        {
                            var bargeName = worksheet.Cells[row, 1].Value?.ToString();
                            if (string.IsNullOrWhiteSpace(bargeName) || bargeName == "")
                            {

UPFleet/Views/Reports/Barge_By_Owner.cshtml
@model List<UPFleet.Models.Barge>
@{
	ViewData["Title"] = "Barge_By_Owner";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
	<div class="function-btn" style="margin-left: 100px;margin-bottom: 20px">
		<a href="@Url.Action("GoBack", "Maintenance")" id="backbtn" class="btn-primary">Back</a>
		<a id="prntbtn" style="display: block"><img src="~/wwwroot/image/printing.png"></a>
		<button class="btn btn-success m-2" id="exportBtn">Export</button>
		<input type="file" id="fileInput" accept=".xlsx, .xls" style="display:none;">
		<button id="importBtn" class="btn btn-success m-2">Import</button>
	</div>
	<div class="row" style="justify-content: center">

		<div class="col-lg-10 border border-2">
			<div class="filterdiv">
				<span>Filter By Owner</span>
				<select id="ownerDropdown" style="width: 30%;" class="form-control form-select home-select">
				</select>
				<hr />
			</div>
			<div class="table-responsive">
				<table class=" table table-striped table-responsive">
					<thead>
						<tr style="text-align: left">
							<th>Barge_Name</th>
							<th>Size</th>
							<th>Rate</th>
							<th>Owner</th>
							<th>Description</th>
						</tr>
					</thead>
					<tbody id="table-body">
					</tbody>
				</table>

			</div>

		</div>
	</div>
	<div id="loader-overlay" style="display:none;">
		<div id="loader" class="popup-loader">
			<div class="spinner">
				<div></div>
				<div></div>
				<div></div>
				<div></div>
				<div></div>
			</div>
			@*<img src="~/wwwroot/image/cargando.gif" style="max-width: 20%;min-width:20%" />*@
		</div>
	</div>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
@section Scripts{
	<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script src="~/wwwroot/js/jsbargereport.js"></script>
}

UPFleet/Views/Reports/Billed_TransferSummary_reportpage.cshtml
@model List<UPFleet.ViewModels.UPFleetViewModel>
@using UPFleet.ViewModels

<html>
<head>
</head>
<body>

    @try
    {
        @{
            var pageQueryString = HttpContext.Current.Request.QueryString["page"];
            var page = !string.IsNullOrEmpty(pageQueryString) ? int.Parse(pageQueryString) : 0;
            const int pageSize = 1; // Set your desired page size here
        }
        <div class="container" id="printTable">
            <div class="function-btn">
                <a href="@Url.Action("GoBack", "Maintenance")" id="backbtn" class="btn-primary">Back</a>
                <a id="prntbtn" title="Print This Report"><img src="~/wwwroot/image/printing.png"></a>
            </div>
        </div>
        @foreach (var item in Model.Skip(page * pageSize).Take(pageSize))
        {
            <div class="p-4 mt-3">
                <div>
                    <div class="row">
                        <div class="col-sm-12 col-md-6">
                            <h4>@item.Owner.Company</h4>
                        </div>
                        <div class="col-sm-12 col-md-6">
                            <h4>@item.Owner.OwnerName</h4>
                        </div>
                    </div>
                    <h4>@item.Owner.Address1</h4>
                    <h4>@item.Owner.Address2</h4>
                    <h4 class="Owner-data">
                        <span>@item.Owner.City</span>
                        <span>@item.Owner.State</span>
                        <span>@item.Owner.Zip</span>
                    </h4>
                </div>
                <div>
                    @foreach (var barge in item.BargeList)
                    {
                        foreach (var tranaction in item.Transactionslist.Where(m => m.Barge == barge.Barge_Name))
                        {
                            <div class="row transactions-head">
                                <div class="col-sm-6 col-md-6 col-6 transactions-data">
                                    <h5>Barge:<span>@tranaction.Barge</span></h5>
                                </div>
                                <div class="col-sm-6 col-md-6 col-6 transactions-data">
                                    <h5>Rate:<span>$@tranaction.Rate</span></h5>
                                </div>
                                <div class="col-sm-6 col-md-6 col-6 transactions-data">
                                    <h5>Status:<span>@tranaction.Status</span></h5>
                                </div>
                                <div class="col-sm-6 col-md-6 col-6 transactions-data">
                                    <h5>Tranaction #:<span>@tranaction.TransactionNo</span></h5>
                                </div>
                            </div>
                            <div class=" table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th width="250px">From</th>
                                            <th>To</th>
                                            <th>Cost</th>
                                            <th>Transfer #</th>
                                            <th>Status</th>
                                            <th>Days In</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var transfer in item.TransferList.Where(m => m.Transaction == tranaction.TransactionNo))
                                        {
                                            <tr>
                                                <td>@transfer.From</td>
                                                <td>@transfer.To</td>
                                                <td>
                                                    $@(transfer.DaysIn * tranaction.Rate)
                                                </td>
                                                <td>@transfer.TransferNO</td>
                                                <td>@transfer.Status</td>
                                                <td>@transfer.DaysIn</td>
                                            </tr>
                                        }
                                        <tr>
                                            <td colspan="6">
                                                <p>Summary for Transaction# @tranaction.TransactionNo (@item.TransferList.Count(m => m.Transaction == tranaction.TransactionNo) details Record)</p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">Sum</td>
                                            @if (tranaction.Rate != null)
                                            {
                                                <td colspan="2">$@((int)(tranaction.Rate) * item.TransferList.Where(m => m.Transaction == tranaction.TransactionNo).Sum(t => t.DaysIn))</td>
                                            }
                                            else
                                            {
                                                <td colspan="2">$0</td>
                                            }

                                            <td colspan="2">@item.TransferList.Where(m => m.Transaction == tranaction.TransactionNo).Sum(t => t.DaysIn)</td>
                                        </tr>

                                    </tbody>
                                </table>
                            </div>

                        }
                    }
                </div>
            </div>
        }
        <div class="container navcontainer" style="">
            <nav aria-label="Page navigation">
                @Html.Partial("PaginationPartial", new PaginationViewModel { TotalPages = (int)Math.Ceiling((double)Model.Count / pageSize), CurrentPage = page })
            </nav>
        </div>
    }
    catch (Exception)
    {
        Response.RedirectToRoute(new { controller = "Error", action = "Index" });

    }
</body>
</html>
@section Scripts{
    <script>
        $(document).ready(function () {
            $("#prntbtn").on("click", function () {
                $(".function-btn").css("display", "none");
                $(".navcontainer").css("display", "none"); // Hide the pagination container
                window.print();
                $(".function-btn").css("display", "initial");
                $(".navcontainer").css("display", "initial"); // Show the pagination container again after printing
            });
        });
    </script>
}

UPFleet/Views/Reports/Not_Billed_TransferSummary_reportpage.cshtml
@model List<UPFleet.ViewModels.UPFleetViewModel>
@using UPFleet.ViewModels

<html>
<head>
</head>
<body>
    @try
    {
        @{
            var pageQueryString = HttpContext.Current.Request.QueryString["page"];
            var page = !string.IsNullOrEmpty(pageQueryString) ? int.Parse(pageQueryString) : 0;
            const int pageSize = 1; // Set your desired page size here
        }
        <div class="container" id="printTable">
            <div class="function-btn">
                <a href="@Url.Action("GoBack", "Maintenance")" id="backbtn" class="btn-primary">Back</a>
                <a id="prntbtn" title="Print This Report"><img src="~/wwwroot/image/printing.png"></a>
            </div>
        </div>
        @foreach (var item in Model.Skip(page * pageSize).Take(pageSize))
        {
            <div class="c">
                <div>
                    <div class="row">
                        <div class="col-sm-12 col-md-6">
                            <h4>@item.Owner.Company</h4>
                        </div>
                        <div class="col-sm-12 col-md-6">
                            <h4>@item.Owner.OwnerName</h4>
                        </div>
                    </div>
                    <h4>@item.Owner.Address1</h4>
                    <h4>@item.Owner.Address2</h4>
                    <h4 class="Owner-data">
                        <span>@item.Owner.City</span>
                        <span>@item.Owner.State</span>
                        <span>@item.Owner.Zip</span>
                    </h4>
                </div>
                <div>
                    @foreach (var barge in item.BargeList)
                    {
                        foreach (var tranaction in item.Transactionslist.Where(m => m.Barge == barge.Barge_Name))
                        {
                            <div class="row transactions-head">
                                <div class="col-sm-6 col-md-6 col-6 transactions-data">
                                    <h5>Barge:<span>@tranaction.Barge</span></h5>
                                </div>
                                <div class="col-sm-6 col-md-6 col-6 transactions-data">
                                    <h5>Rate:<span>$@tranaction.Rate</span></h5>
                                </div>
                                <div class="col-sm-6 col-md-6 col-6 transactions-data">
                                    <h5>Status:<span>@tranaction.Status</span></h5>
                                </div>
                                <div class="col-sm-6 col-md-6 col-6 transactions-data">
                                    <h5>Tranaction #:<span>@tranaction.TransactionNo</span></h5>
                                </div>
                            </div>
                            <div class=" table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th width="250px">From</th>
                                            <th>To</th>
                                            <th>Cost</th>
                                            <th>Transfer #</th>
                                            <th>Status</th>
                                            <th>Days In</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var transfer in item.TransferList.Where(m => m.Transaction == tranaction.TransactionNo))
                                        {
                                            <tr>
                                                <td>@transfer.From</td>
                                                <td>@transfer.To</td>
                                                @if (tranaction.Rate != null)
                                                {
                                                    <td>
                                                        $@(transfer.DaysIn * tranaction.Rate)
                                                    </td>
                                                }
                                                else
                                                {
                                                    <td>
                                                        $0
                                                    </td>
                                                }

                                                <td>@transfer.TransferNO</td>
                                                <td>@transfer.Status</td>
                                                @if (transfer.DaysIn != null)
                                                {
                                                    <td>
                                                        $@(transfer.DaysIn )
                                                    </td>
                                                }
                                                else
                                                {
                                                    <td>
                                                        0
                                                    </td>
                                                }
                                            </tr>
                                        }
                                        <tr>
                                            <td colspan="6">
                                                <p>Summary for Transaction# @tranaction.TransactionNo (@item.TransferList.Count(m => m.Transaction == tranaction.TransactionNo) details Record)</p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">Sum</td>
                                            @if (tranaction.Rate != null)
                                            {
                                                <td colspan="2">
                                                    $@((tranaction.Rate) * item.TransferList.Where(m => m.Transaction == tranaction.TransactionNo).Sum(t => t.DaysIn))
                                                </td>
                                            }
                                            else
                                            {
                                                <td colspan="2">$0</td>
                                            }
                                            <td colspan="2">@item.TransferList.Where(m => m.Transaction == tranaction.TransactionNo).Sum(t => t.DaysIn)</td>
                                        </tr>

                                    </tbody>
                                </table>
                            </div>

                        }
                    }
                </div>
            </div>
        }
        <div class="container navcontainer" style="">
            <nav aria-label="Page navigation">
                @Html.Partial("PaginationPartial", new PaginationViewModel { TotalPages = (int)Math.Ceiling((double)Model.Count / pageSize), CurrentPage = page })
            </nav>
        </div>


    }
    catch (Exception)
    {
        Response.RedirectToRoute(new { controller = "Error", action = "Index" });

    }
</body>
</html>
@section Scripts{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#prntbtn").on("click", function () {
                $(".function-btn").css("display", "none");
                $(".navcontainer").css("display", "none"); // Hide the pagination container
                window.print();
                $(".function-btn").css("display", "initial");
                $(".navcontainer").css("display", "initial"); // Show the pagination container again after printing
            });
        });
    </script>
}

UPFleet/Views/Reports/Owner_reports.cshtml
@model List<UPFleet.Models.Owner>
@{
    ViewData["Title"] = "Owner_reports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">

    <div class="function-btn" style="margin-bottom: 15px; margin-left: -10px;">
        <a href="@Url.Action("GoBack", "Maintenance")" id="backbtn" class="btn-primary">Back</a>
        <a id="prntbtn" title="Print This Report"><img src="~/wwwroot/image/printing.png"></a>
    </div>
    <div class="row" style="justify-content: center">

        <div class="col-lg-12 table-responsive">

            <table class=" table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>OwnerName</th>
                        <th>Company</th>
                        <th>Address1</th>
                        <th>Address2</th>
                        <th>City</th>
                        <th>State</th>
                        <th>Zip</th>
                        <th>Account</th>

                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.OwnerName</td>
                            <td>@item.Company</td>
                            <td>@item.Address1</td>
                            <td>@item.Address2</td>
                            <td>@item.City</td>
                            <td>@item.State</td>
                            <td>@item.Zip</td>
                            <td>@item.Account</td>
                        </tr>

                    }
                </tbody>
            </table>

        </div>

    </div>
</div>
@section Scripts{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#prntbtn").click(function () {
                $(".function-btn").hide();
                window.print();
                $(".function-btn").show();
            });
        });
    </script>
}

UPFleet/Views/Reports/PreviewToExport_Page.cshtml
@model List<UPFleet.ViewModels.UPFleetViewModel>

<html>
<head>
</head>
<body>

    <div class="function-btn">
        <a href="@Url.Action("GoBack", "Maintenance")" id="backbtn" class="btn-primary">Back</a>
        <a id="prntbtn" title="Print This Report"><img src="~/wwwroot/image/printing.png"></a>
    </div>
    <div class="filterdiv">
        <span>Filter By Owner</span>
        <select id="ownerDropdown" style="width: 30%;" class="form-control form-select home-select">
        </select>
        <span>Filter By Transaction Status</span>
        <select id="transStatusDropdown" style="width: 30%;" class="form-control form-select home-select">
            <option value="Select Status">Select Status/None</option>
            <option value="In">In</option>
            <option value="Out">Out</option>
            <option value="Last switched">Last switched</option>
            <option value="To Bill">To Bill</option>
            <option value="Billed">Billed</option>
        </select>
        <label for="fromDate">From Date:</label>
        <input type="date" id="fromDate" name="fromDate">

        <label for="toDate">To Date:</label>
        <input type="date" id="toDate" name="toDate">
        <hr />
    </div>
    <table class="table" id="printTable">
        <thead>
            <tr>
                <th>Barge Name</th>
                <th>Owner</th>
                <th>Total Cost</th>
                <th>Transaction No</th>
                <th>Barge Size</th>
                <th>Rate</th>
                <th>Total Days</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody id="transactiontable-body">
            
        </tbody>
    </table>
    <div id="loader-overlay" style="display:none;">
        <div id="loader" class="popup-loader">
            <div class="spinner">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
            @*<img src="~/wwwroot/image/cargando.gif" style="max-width: 20%;min-width:20%" />*@
        </div>
    </div>
</body>
</html>
@section Scripts{
    <script src="~/wwwroot/js/jspreviewtoexport.js"></script>
}